### ISSUE TITLE
Add arm docker image for raspberry pi zero

### ISSUE THREAD

**Issue by nriel** [wimaha/TeslaBleHttpProxy#32]
I can't use the docker image due to wrong architecture

**Comment by dglaude** [comment]
I think the image is arm64 and on 32 bit arm (armv6?) like PiZero, you would need armhf.
Not sure it will run or it is still possible/easy to run docker on a PiZero. It would be more easy on a PiZero 2W that would be able to run the arm64 container.

Maybe the topic could be enhanced a little bit and also have also a docker image that works on x86-64 to run on an Intel NUC or that kind of small size computer.

**Comment by nriel** [comment]
I see the following error:
 tesla-ble-http-proxy The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v6) and no specific platform
 was requested 0.0s 
Attaching to tesla-ble-http-proxy
tesla-ble-http-proxy  | exec /teslaBleHttpProxy: exec format error
tesla-ble-http-proxy exited with code 0

Docker in general works fine, but only with supported images.

In order to get going, I installed the proxy as a go-application and it is running fine.
Only thing I can't get to work is to load it as a systemd service on boot.  It always complains about the certificate not being found. I already tried to put it into /root/key/*cert, but that does not seem to be the path being searched for.
When building, I added the cert to the /key folder and while running with ./TeslaBleHttpProxy it also does start correctly with the certifcates found in the root folder of TeslaBleHttpProxy

**Comment by little-penguin88** [comment]
I made a start script which changes to the TeslaBleHttpProxy dir and then in there let ./TeslaBleHttpProxy start. so it works with the /key folder in that dir. And then I added that script to a @startup cron job

**Comment by nriel** [comment]
Could you please share the script? Thanks!

**Comment by little-penguin88** [comment]
Sure. I called it StartTeslaProxy.sh
```
cd TeslaBleHttpProxy
./TeslaBleHttpProxy > TeslaProxy.log 2>&1 &
````
You then need to make it executable with

`chmod +x StartTeslaProxy.sh`

And then add it to crontab with

`crontab -e`

and in that file just paste `@reboot /PathToYourScript/StartTeslaProxy.sh`

**Comment by ugoetzen** [comment]
Same here. I got an PiZero 2W and cant get it running due to the wrong platform.

**Comment by wimaha** [comment]
I will try adding this binarys in the docker image. I come back here, when it‘s completed.

**Comment by wimaha** [comment]
Can you try via `wimaha/tesla-ble-http-proxy:dev` if it's working?

**Comment by ugoetzen** [comment]
Just gave it a try on a PiZero 2W:
```
root@raspible:/home/udo/TeslaBleHttpProxy# docker pull wimaha/tesla-ble-http-proxy:dev
dev: Pulling from wimaha/tesla-ble-http-proxy
be490e8d6aa6: Pull complete 
6be72e41f1a7: Pull complete 
017206a48663: Pull complete 
Digest: sha256:e910b36091c21b4c45b4b972cc143cce58251f028f45c8958f11fedce1cae296
Status: Downloaded newer image for wimaha/tesla-ble-http-proxy:dev
docker.io/wimaha/tesla-ble-http-proxy:dev
root@raspible:/home/udo/TeslaBleHttpProxy# docker compose up
[+] Running 2/1
 ✔ Container tesla-ble-http-proxy                                                                                                                                    Created                                                   0.5s 
 ! tesla-ble-http-proxy The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested                                                           0.0s 
Attaching to tesla-ble-http-proxy
tesla-ble-http-proxy  | exec /teslaBleHttpProxy: exec format error
tesla-ble-http-proxy exited with code 0
```
seems the platform is still not the right one.

**Comment by swa72** [comment]
I'm a noob myself when it comes to docker, but ...

```
services:
  tesla-ble-http-proxy:
    image: wimaha/tesla-ble-http-proxy:dev
    container_name: tesla-ble-http-proxy
    volumes:
      - ~/TeslaBleHttpProxy/key:/key
      - /var/run/dbus:/var/run/dbus
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
```
that got me going :-) Note the different image name.

**Comment by nriel** [comment]
On Raspberry pi zero W still crashing with error 132

**Comment by wimaha** [comment]
Should be working with Version 1.2.2 now. If there are any other errors, please open new issue.

**Comment by nriel** [comment]
With raspberry pi zero w still getting code error 132.

dpkg --print-architecture shows:
armhf

**Comment by lits101** [comment]
> With raspberry pi zero w still getting code error 132.
> 
> dpkg --print-architecture shows: armhf

I'm also getting error 132 on a Raspberry Pi Zero W.

**Comment by wimaha** [comment]
There is a new version on dev tag. Can some one test this with Raspberry Pi Zero W?

`image: wimaha/tesla-ble-http-proxy:dev`

**Comment by wimaha** [comment]
I've release the version with 1.2.5

**Comment by lits101** [comment]
I've just spun up a new instance of 1.2.5 in docker-compose on a Raspberry Pi 0 W and I can confirm I'm still getting the "Restarting (132)" error.

```
pi@teslaproxy2:~/teslableproxy $ docker ps
CONTAINER ID   IMAGE                         COMMAND                CREATED          STATUS                           PORTS     NAMES
e01a5844ad69   wimaha/tesla-ble-http-proxy   "/teslaBleHttpProxy"   59 seconds ago   Restarting (132) 9 seconds ago             tesla-ble-http-proxy
```

**Comment by sovathnahim** [comment]
How the program can communication to the car ?

Do you mean , we need to connect wifi to raspi with we installed "TeslaBleHttpProxy"?
I still do not understand, the instruction to do it ? after input the Tesla Vin , we need to scanned the new Key card or just the known current tesla Keycard, basically tesla need to confirm by paired key card every time we set up andy key card , phone or remote.
Actually , I am successfully installed it but not yet testing, So please kindly advice , thanks

**Comment by AloisKlingler** [comment]
also here on a pi zero 1 w with error 132
is there any workaround available?

**Comment by wimaha** [comment]
It is possible to compile the program on the Zero 1 W yourself. So far, I haven’t found a solution using Docker. I’ve tried a few things, but since I don’t own a Zero 1 W myself, I can’t test it thoroughly. This is an open-source project, so feel free to submit a PR with a solution. ☺️

**Comment by little-penguin88** [comment]
Just compile it yourself. It is very straight forward actually if you
follow the instructions to compile the sources your own. I have done it as
well on a Zero 1 W. Only thing is you need to give the installation time to
finish. So if you you think it is no longer responding... Have a coffee and
look again half an hour later

Wilko ***@***.***> schrieb am Mi., 25. Dez. 2024, 20:38:

**Comment by AloisKlingler** [comment]
@wimaha I tried to find where you define your docker build, but I could not.
building manually works also on old rpi0 well.
can you try the solution for the docker build here? https://stackoverflow.com/questions/66116587/docker-buildx-mulitarch-armv6

**Comment by AloisKlingler** [comment]
@wimaha hier wurde für evcc das gleiche problem behoben: https://github.com/evcc-io/evcc/pull/17959

die passende diskussion dazu: https://github.com/evcc-io/evcc/discussions/10555

ich hoffe das hilft. :-)

**Comment by AloisKlingler** [comment]
> It is possible to compile the program on the Zero 1 W yourself. So far, I haven’t found a solution using Docker. I’ve tried a few things, but since I don’t own a Zero 1 W myself, I can’t test it thoroughly. This is an open-source project, so feel free to submit a PR with a solution. ☺️

I submitted an PR now at https://github.com/wimaha/TeslaBleHttpProxy/pull/70

**Comment by wimaha** [comment]
New version with the PR #70 from @AloisKlingler is online in dev.

**Comment by AloisKlingler** [comment]
🥳 this docker image works for me on the rpi zero 1 with armv6

**Comment by wimaha** [comment]
Very nice! :-)

**Comment by wimaha** [comment]
Release 2.0.2 should work.

**Comment by swa72** [comment]
How do I get a newer release? I'm currently running Version 1.2 with this installation https://github.com/wimaha/TeslaBleHttpProxy/issues/32#issuecomment-2254572561. How can I update to the latest version? I've tried 

```
docker pull wimaha/tesla-ble-http-proxy
docker compose up -d
```

but the same version starts. Duh

**Comment by wimaha** [comment]
@swa72 I can add this. But it is not recommended to always use dev channel. Sometimes there are experimental versions. So please use `wimaha/tesla-ble-http-proxy` in the docker compose and to update.

**Comment by swa72** [comment]
@wimaha I'm running the proxy on a PiZero and just pulling with `wimaha/tesla-ble-http-proxy` did not do the job for me. I simply wasn't aware that I need to add `:dev` to get the right architecture.  If whatever is in the dev part makes it to the main part, I'm happy to use that.

**Comment by wimaha** [comment]
There is are not different architectures in the dev channel. Right now the version in dev is the same as the latest release. It is recommended to remove the `:dev` in the docker compose file.
